import Header from './Header/Header';
import Footer from './Footer/Footer';
import Layout from './MainLayout/Layout';
import Container from './Container/Container';
import Skills from './Skills/Skills';
import Projects from './Projects/Projects';
import Contact from './Contact/Contact';
import About from './About/About';
import Experience from "./Experience/Experience";
import Education from './Education/Education';
export {Header, Footer, Layout, Container, Skills,Projects,Contact,About,Experience,Education};